[package]
name = "sebeke"
version = "0.1.0"
edition = "2024"
description = "Distributed serverless-first infrastructure for robotics"


# The primary infrastructure library
[lib]
name = "sebeke"
path = "src/sebeke/lib.rs"

[dependencies]
# Backbone & Transport
zenoh = "1.8.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "rt", "time"] }

# Serialization (CBOR for inter-node, JSON for Zenoh/Cloud interop)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ciborium = "0.2.2"

# Networking & Cloud Interop
# Using multipart features for binary-safe media transfers
reqwest = { version = "0.13.2", default-features = false, features = ["json", "multipart", "rustls"] }
url = "2.4"

# Utils
clap = { version = "4.6.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
anyhow = "1.0.102"
async-trait = "0.1.89"
regex = "1.12.3"
dashmap = "6.1.0"
futures = "0.3.32"
serde_bytes = "0.11.19"
axum = { version = "0.8.9", features = ["multipart"] }
tokio-stream = "0.1.18"
bytes = "1.11.1"
axum-extra = "0.12.6"
multer = "3.1.0"
moka = { version = "0.12.15", features = ["sync"] }
ratatui = "0.30.0"
crossterm = "0.29.0"
tracing = "0.1.44"


[dev-dependencies]
# Moved teloxide here as it's currently for illustration
teloxide = "0.11"

# A specific executable node
[[bin]]
name = "telegram_node"
path = "src/nodes/telegram/main.rs"

[[bin]]
name = "tui_node"
path = "src/nodes/tui/main.rs"
